spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    password: bank_pwd
    username: bank_user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql

server:
  port: 7788